/* Generated by Yosys 0.62 (git sha1 v0.62, g++ 15.2.0 -fPIC -O3) */

module CART(CLK, RST_N, ENABLE, ROM_MODE, RAM_ID, VA, VDI, AS_N, RNW, LDS_N, UDS_N, ASEL_N, VCLK_CE, CE0_N, ROM_DI, ROM_RDY, RAM_DI, RAM_RDY, VDO, DTACK_N, CART_N
, ROM_CE_N, RAM_CE_N);
  input CLK;
  wire CLK;
  input RST_N;
  wire RST_N;
  input ENABLE;
  wire ENABLE;
  input ROM_MODE;
  wire ROM_MODE;
  input [7:0] RAM_ID;
  wire [7:0] RAM_ID;
  input [22:0] VA;
  wire [22:0] VA;
  input [15:0] VDI;
  wire [15:0] VDI;
  input AS_N;
  wire AS_N;
  input RNW;
  wire RNW;
  input LDS_N;
  wire LDS_N;
  input UDS_N;
  wire UDS_N;
  input ASEL_N;
  wire ASEL_N;
  input VCLK_CE;
  wire VCLK_CE;
  input CE0_N;
  wire CE0_N;
  input [15:0] ROM_DI;
  wire [15:0] ROM_DI;
  input ROM_RDY;
  wire ROM_RDY;
  input [15:0] RAM_DI;
  wire [15:0] RAM_DI;
  input RAM_RDY;
  wire RAM_RDY;
  output [15:0] VDO;
  wire [15:0] VDO;
  output DTACK_N;
  wire DTACK_N;
  output CART_N;
  wire CART_N;
  output ROM_CE_N;
  wire ROM_CE_N;
  output RAM_CE_N;
  wire RAM_CE_N;
  wire _000_;
  wire _001_;
  reg [1:0] _002_;
  reg _003_;
  reg _004_;
  reg [15:0] _005_;
  reg [15:0] _006_;
  reg [7:0] _007_;
  wire _008_;
  wire _009_;
  wire [1:0] _010_;
  wire _011_;
  wire _012_;
  wire [1:0] _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire [1:0] _018_;
  wire _019_;
  wire [1:0] _020_;
  wire _021_;
  wire [15:0] _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire [1:0] _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire [1:0] _032_;
  wire _033_;
  wire [15:0] _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire [1:0] _056_;
  wire _057_;
  wire [15:0] _058_;
  wire [7:0] _059_;
  wire _060_;
  wire _061_;
  wire [1:0] _062_;
  wire _063_;
  wire [15:0] _064_;
  wire [7:0] _065_;
  wire _066_;
  wire [1:0] _067_;
  wire _068_;
  wire [15:0] _069_;
  wire [7:0] _070_;
  wire _071_;
  wire _072_;
  wire [1:0] _073_;
  wire _074_;
  wire [15:0] _075_;
  wire [7:0] _076_;
  wire _077_;
  wire _078_;
  wire [1:0] _079_;
  wire _080_;
  wire [1:0] _081_;
  wire _082_;
  wire _083_;
  wire [15:0] _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire [1:0] _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire [1:0] _093_;
  wire _094_;
  wire _095_;
  wire [15:0] _096_;
  wire [7:0] _097_;
  wire _098_;
  wire [15:0] _099_;
  wire _100_;
  wire _101_;
  reg _102_;
  reg _103_;
  reg [1:0] _104_;
  wire [15:0] cart_ram_do;
  wire cart_ram_dtack_n;
  wire cart_ram_sel;
  wire [7:0] cart_ram_wp;
  wire [15:0] cart_rom_do;
  wire cart_rom_dtack_n;
  wire cart_rom_sel;
  wire [1:0] rams;
  wire [1:0] roms;
  assign _061_ = ~ ASEL_N;
  assign _055_ = _060_ ? 1'h0 : _103_;
  assign _056_ = _054_ ? 2'h1 : 2'h3;
  assign _057_ = _054_ ? cart_ram_dtack_n : 1'h0;
  assign _072_ = _061_ & _050_;
  assign _058_ = RNW ? { 8'hff, cart_ram_wp } : cart_ram_do;
  assign _059_ = RNW ? cart_ram_wp : VDI[7:0];
  assign _060_ = _054_ & _048_;
  assign _062_ = _048_ ? _056_ : 2'h3;
  assign _063_ = _048_ ? _057_ : 1'h0;
  assign _064_ = _048_ ? cart_ram_do : _058_;
  assign _065_ = _048_ ? cart_ram_wp : _059_;
  assign _066_ = VA[20] ? _055_ : _103_;
  assign _083_ = _072_ ? ROM_MODE : 1'h0;
  assign _067_ = VA[20] ? _062_ : 2'h3;
  assign _068_ = VA[20] ? _063_ : 1'h0;
  assign _069_ = VA[20] ? _064_ : { 8'hff, RAM_ID };
  assign _070_ = VA[20] ? _065_ : cart_ram_wp;
  assign _071_ = _046_ ? _066_ : _103_;
  assign _073_ = _046_ ? _067_ : rams;
  assign _074_ = _046_ ? _068_ : cart_ram_dtack_n;
  assign _075_ = _046_ ? _069_ : cart_ram_do;
  assign _076_ = _046_ ? _070_ : cart_ram_wp;
  assign _077_ = ! rams;
  assign _078_ = ~ RAM_RDY;
  assign _079_ = RAM_RDY ? rams : 2'h2;
  assign _080_ = rams == 2'h1;
  assign _081_ = RAM_RDY ? 2'h3 : rams;
  assign _082_ = RAM_RDY ? 1'h0 : cart_ram_dtack_n;
  assign _084_ = RAM_RDY ? { 8'hff, RAM_DI[7:0] } : cart_ram_do;
  assign _085_ = rams == 2'h2;
  assign _086_ = ~ cart_ram_dtack_n;
  assign _087_ = ASEL_N & _086_;
  assign _088_ = _087_ ? 1'h1 : _103_;
  assign _089_ = _087_ ? 2'h0 : rams;
  assign _090_ = _087_ ? 1'h1 : cart_ram_dtack_n;
  assign _091_ = rams == 2'h3;
  function [0:0] \:159 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:159  = b[0:0];
      4'b??1?:
        \:159  = b[1:1];
      4'b?1??:
        \:159  = b[2:2];
      4'b1???:
        \:159  = b[3:3];
      default:
        \:159  = a;
    endcase
  endfunction
  assign _092_ = \:159 (_103_, { _088_, _103_, _103_, _071_ }, { _091_, _085_, _080_, _077_ });
  assign _094_ = ~ RST_N;
  function [1:0] \:160 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:160  = b[1:0];
      4'b??1?:
        \:160  = b[3:2];
      4'b?1??:
        \:160  = b[5:4];
      4'b1???:
        \:160  = b[7:6];
      default:
        \:160  = a;
    endcase
  endfunction
  assign _093_ = \:160 (rams, { _089_, _081_, _079_, _073_ }, { _091_, _085_, _080_, _077_ });
  function [0:0] \:161 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:161  = b[0:0];
      4'b??1?:
        \:161  = b[1:1];
      4'b?1??:
        \:161  = b[2:2];
      4'b1???:
        \:161  = b[3:3];
      default:
        \:161  = a;
    endcase
  endfunction
  assign _095_ = \:161 (cart_ram_dtack_n, { _090_, _082_, cart_ram_dtack_n, _074_ }, { _091_, _085_, _080_, _077_ });
  function [15:0] \:162 ;
    input [15:0] a;
    input [63:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:162  = b[15:0];
      4'b??1?:
        \:162  = b[31:16];
      4'b?1??:
        \:162  = b[47:32];
      4'b1???:
        \:162  = b[63:48];
      default:
        \:162  = a;
    endcase
  endfunction
  assign _096_ = \:162 (cart_ram_do, { cart_ram_do, _084_, cart_ram_do, _075_ }, { _091_, _085_, _080_, _077_ });
  function [7:0] \:163 ;
    input [7:0] a;
    input [31:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:163  = b[7:0];
      4'b??1?:
        \:163  = b[15:8];
      4'b?1??:
        \:163  = b[23:16];
      4'b1???:
        \:163  = b[31:24];
      default:
        \:163  = a;
    endcase
  endfunction
  assign _097_ = \:163 (cart_ram_wp, { cart_ram_wp, cart_ram_wp, cart_ram_wp, _076_ }, { _091_, _085_, _080_, _077_ });
  assign _001_ = cart_rom_dtack_n & cart_rom_sel;
  assign _098_ = ~ cart_rom_dtack_n;
  assign _099_ = _003_ ? cart_ram_do : cart_rom_do;
  assign _100_ = cart_rom_dtack_n & cart_ram_dtack_n;
  assign _101_ = ~ ROM_MODE;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _102_ <= 1'h1;
    else _102_ <= _031_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _103_ <= 1'h1;
    else _103_ <= _092_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _104_ <= 2'h0;
    else _104_ <= _032_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _002_ <= 2'h0;
    else _002_ <= _093_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _003_ <= 1'h1;
    else _003_ <= _033_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _004_ <= 1'h1;
    else _004_ <= _095_;
  assign _008_ = ~ RNW;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _005_ <= 16'h0000;
    else _005_ <= _034_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _006_ <= 16'h0000;
    else _006_ <= _096_;
  always @(posedge CLK, negedge RST_N)
    if (!RST_N) _007_ <= 8'hff;
    else _007_ <= _097_;
  assign _009_ = RNW ? 1'h0 : _102_;
  assign _010_ = RNW ? 2'h1 : 2'h3;
  assign _011_ = _014_ ? 1'h0 : cart_rom_dtack_n;
  assign _012_ = _001_ ? _009_ : _102_;
  assign _013_ = _001_ ? _010_ : roms;
  assign _014_ = _008_ & _001_;
  assign _015_ = ! roms;
  assign _016_ = ~ ROM_RDY;
  assign _018_ = ROM_RDY ? roms : 2'h2;
  assign _019_ = roms == 2'h1;
  assign _020_ = ROM_RDY ? 2'h3 : roms;
  assign _021_ = ROM_RDY ? 1'h0 : cart_rom_dtack_n;
  assign _022_ = ROM_RDY ? ROM_DI : cart_rom_do;
  assign _023_ = roms == 2'h2;
  assign _024_ = ~ cart_rom_dtack_n;
  assign _025_ = ASEL_N & _024_;
  assign _026_ = _025_ ? 1'h1 : _102_;
  assign _027_ = _025_ ? 2'h0 : roms;
  assign _000_ = ~ CE0_N;
  assign _029_ = _025_ ? 1'h1 : cart_rom_dtack_n;
  assign _030_ = roms == 2'h3;
  function [0:0] \:55 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:55  = b[0:0];
      4'b??1?:
        \:55  = b[1:1];
      4'b?1??:
        \:55  = b[2:2];
      4'b1???:
        \:55  = b[3:3];
      default:
        \:55  = a;
    endcase
  endfunction
  assign _031_ = \:55 (_102_, { _026_, _102_, _102_, _012_ }, { _030_, _023_, _019_, _015_ });
  function [1:0] \:56 ;
    input [1:0] a;
    input [7:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:56  = b[1:0];
      4'b??1?:
        \:56  = b[3:2];
      4'b?1??:
        \:56  = b[5:4];
      4'b1???:
        \:56  = b[7:6];
      default:
        \:56  = a;
    endcase
  endfunction
  assign _032_ = \:56 (roms, { _027_, _020_, _018_, _013_ }, { _030_, _023_, _019_, _015_ });
  function [0:0] \:57 ;
    input [0:0] a;
    input [3:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:57  = b[0:0];
      4'b??1?:
        \:57  = b[1:1];
      4'b?1??:
        \:57  = b[2:2];
      4'b1???:
        \:57  = b[3:3];
      default:
        \:57  = a;
    endcase
  endfunction
  assign _033_ = \:57 (cart_rom_dtack_n, { _029_, _021_, cart_rom_dtack_n, _011_ }, { _030_, _023_, _019_, _015_ });
  function [15:0] \:58 ;
    input [15:0] a;
    input [63:0] b;
    input [3:0] s;
    casez (s) // synopsys parallel_case
      4'b???1:
        \:58  = b[15:0];
      4'b??1?:
        \:58  = b[31:16];
      4'b?1??:
        \:58  = b[47:32];
      4'b1???:
        \:58  = b[63:48];
      default:
        \:58  = a;
    endcase
  endfunction
  assign _034_ = \:58 (cart_rom_do, { cart_rom_do, _022_, cart_rom_do, cart_rom_do }, { _030_, _023_, _019_, _015_ });
  assign _017_ = ~ LDS_N;
  assign _028_ = ~ UDS_N;
  assign _035_ = ~ ROM_MODE;
  assign _036_ = ~ CE0_N;
  assign _037_ = ~ LDS_N;
  assign _038_ = ~ UDS_N;
  assign _040_ = _037_ | _038_;
  assign _041_ = _040_ & _036_;
  assign _042_ = ~ ASEL_N;
  assign _043_ = _042_ & _041_;
  assign _039_ = _017_ | _028_;
  assign _044_ = _043_ ? _035_ : 1'h0;
  assign _045_ = ~ RST_N;
  assign _046_ = cart_ram_dtack_n & cart_ram_sel;
  assign _047_ = ~ VA[20];
  assign _050_ = _039_ & _000_;
  assign _048_ = VA[20:19] == 2'h2;
  assign _049_ = ~ RNW;
  assign _051_ = ~ LDS_N;
  assign _052_ = _051_ & _049_;
  assign _053_ = cart_ram_wp[0] & _052_;
  assign _054_ = RNW | _053_;
  assign roms = _104_;
  assign rams = _002_;
  assign cart_rom_sel = _083_;
  assign cart_ram_sel = _044_;
  assign cart_rom_dtack_n = _003_;
  assign cart_ram_dtack_n = _004_;
  assign cart_rom_do = _005_;
  assign cart_ram_do = _006_;
  assign cart_ram_wp = _007_;
  assign VDO = _099_;
  assign DTACK_N = _100_;
  assign CART_N = _101_;
  assign ROM_CE_N = _102_;
  assign RAM_CE_N = _103_;
endmodule
